version: '3'
services:
  esxi-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-esxi-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_esxi_api:/usr/lib/python3.6/site-packages/vlab_esxi_api
    command: ["python3", "app.py"]

  esxi-worker:
    image:
      willnx/vlab-esxi-worker
    volumes:
      - ./vlab_esxi_api:/usr/lib/python3.6/site-packages/vlab_esxi_api
      - /mnt/raid/images/esxi:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  esxi-broker:
    image:
      rabbitmq:3.7-alpine
